import { BoardState, Decision, DecisionMetrics, ProjectStats } from "./execution-types";

export const mockExecutionBoard: BoardState = {
  planning: [
    {
      id: "PRJ-001",
      title: "New Product Launch - Organic Juice Line",
      linkedOperations: ["INV-2847", "PROD-1125"],
      priority: "high",
      dueDate: "2025-12-15",
      assignees: ["John D.", "Sarah M."],
      completionRate: 15,
      decisionsPending: 3,
      aiRisk: "medium",
      dependencies: ["Supplier certification", "QA protocol setup"],
      inventoryLink: {
        items: ["Raw materials secured", "80% packaging ready"],
        alerts: ["Low stock on organic oranges"],
      },
    },
    {
      id: "PRJ-002",
      title: "Cold Storage Expansion",
      linkedOperations: ["WH-COLD-01"],
      priority: "critical",
      dueDate: "2025-11-30",
      assignees: ["Mike R.", "Lisa K."],
      completionRate: 45,
      decisionsPending: 1,
      aiRisk: "low",
      dependencies: ["Budget approval", "Contractor selection"],
    },
  ],
  inProgress: [
    {
      id: "PRJ-003",
      title: "HACCP Compliance Upgrade",
      linkedOperations: ["QA-PROC-001"],
      priority: "high",
      dueDate: "2025-11-20",
      assignees: ["QA Team"],
      completionRate: 72,
      decisionsPending: 0,
      aiRisk: "low",
      currentPhase: "Documentation review",
    },
    {
      id: "PRJ-004",
      title: "Stockout Resolution - SKU-4589",
      linkedOperations: ["INV-4589", "PO-11250"],
      priority: "critical",
      dueDate: "2025-11-18",
      assignees: ["Procurement"],
      completionRate: 60,
      decisionsPending: 2,
      aiRisk: "high",
      autoGenerated: true,
      aiAgent: "InventoryAgent",
    },
  ],
  review: [
    {
      id: "PRJ-005",
      title: "Q4 Production Planning",
      linkedOperations: ["PROD-PLAN-Q4"],
      priority: "medium",
      dueDate: "2025-11-25",
      assignees: ["Production Team"],
      completionRate: 90,
      decisionsPending: 1,
      aiRisk: "low",
      awaitingApproval: true,
    },
  ],
  completed: [
    {
      id: "PRJ-006",
      title: "Supplier Onboarding - Green Valley",
      linkedOperations: ["SUPP-GV-001"],
      priority: "medium",
      completedDate: "2025-11-10",
      assignees: ["Procurement"],
      completionRate: 100,
      decisionsLogged: 5,
      outcomes: "Successfully onboarded with 98% compliance",
    },
  ],
};

export const mockProjectStats: ProjectStats = {
  activeProjects: { value: 8, trend: "+2" },
  atRisk: { value: 2, trend: "0", alert: true },
  dueThisWeek: { value: 3, trend: "-1" },
  aiGenerated: { value: 4, trend: "+1" },
  decisionsPending: { value: 7, trend: "+3", alert: true },
  completedMtd: { value: 12, trend: "+5", success: true },
};

export const mockDecisions: Decision[] = [
  {
    id: "DEC-2025-001",
    title: "Approve Emergency Procurement - Organic Milk Shortage",
    module: "procurement",
    stakes: "high",
    status: "pending",
    requester: "InventoryAgent",
    created: "2025-11-15T10:30:00Z",
    deadline: "2025-11-15T18:00:00Z",
    context: {
      currentStock: "200 gallons",
      dailyDemand: "150 gallons",
      leadTime: "2 days",
      alternativeSuppliers: 3,
    },
    alternatives: [
      {
        option: "Emergency order from Green Valley (premium supplier)",
        cost: "$4,500",
        deliveryTime: "12 hours",
        quality: "Premium",
        aiScore: 92,
      },
      {
        option: "Standard order from Miller Farms",
        cost: "$3,200",
        deliveryTime: "24 hours",
        quality: "Standard",
        aiScore: 78,
      },
      {
        option: "Split order between two suppliers",
        cost: "$3,900",
        deliveryTime: "16 hours",
        quality: "Mixed",
        aiScore: 85,
      },
    ],
    criteria: ["Cost", "Delivery Speed", "Quality Standards", "Supplier Reliability"],
    noiseFactors: {
      anchoring: {
        detected: true,
        severity: "medium",
        description: "Focusing on previous supplier pricing",
      },
      availability: { detected: false },
      confirmation: {
        detected: true,
        severity: "low",
        description: "Preference for known supplier",
      },
    },
    aiRecommendation: {
      choice: "Option 1 - Emergency order from Green Valley",
      confidence: 92,
      reasoning:
        "Critical stock situation requires fastest delivery. Quality premium justified by customer retention risk.",
    },
    stakeholders: ["Procurement Manager", "Finance", "Operations", "Quality Team"],
  },
  {
    id: "DEC-2025-002",
    title: "QA Protocol Exception - Batch B2025-1115-A",
    module: "quality",
    stakes: "critical",
    status: "pending",
    requester: "QA Team",
    created: "2025-11-15T09:00:00Z",
    deadline: "2025-11-15T16:00:00Z",
    context: {
      batchSize: "500kg",
      testResults: "Marginal fail on one parameter",
      customerImpact: "High-priority order",
      riskAssessment: "Low health risk",
    },
    alternatives: [
      {
        option: "Accept with conditions",
        risk: "Low",
        customerImpact: "None",
        compliance: "Documented exception",
        aiScore: 88,
      },
      {
        option: "Reject and retest",
        risk: "None",
        customerImpact: "2-day delay",
        compliance: "Full compliance",
        aiScore: 75,
      },
      {
        option: "Partial acceptance",
        risk: "Very Low",
        customerImpact: "Partial fulfillment",
        compliance: "Documented",
        aiScore: 82,
      },
    ],
    criteria: ["Safety", "Customer Service", "Compliance", "Financial Impact"],
    noiseFactors: {
      anchoring: { detected: false },
      availability: {
        detected: true,
        severity: "high",
        description: "Recent similar case influencing judgment",
      },
      confirmation: { detected: false },
    },
    aiRecommendation: {
      choice: "Option 1 - Accept with conditions",
      confidence: 88,
      reasoning:
        "Historical data shows 98% success rate with similar marginal failures. Risk within acceptable limits.",
    },
    stakeholders: ["QA Manager", "Production", "Customer Service", "Compliance Officer"],
  },
];

export const mockDecisionMetrics: DecisionMetrics = {
  totalDecisions: 247,
  pendingDecisions: 7,
  avgDecisionTime: "4.2 hours",
  consistencyScore: 87,
  noiseReduction: "+23%",
  aiAcceptanceRate: 78,
  overdueDecisions: 2,
};
