export const columnOrder = ["planning", "inProgress", "review", "completed"] as const;
export type ColumnKey = (typeof columnOrder)[number];

export type Priority = "critical" | "high" | "medium" | "low";
export type RiskLevel = "high" | "medium" | "low";

export type Project = {
  id: string;
  title: string;
  linkedOperations?: string[];
  priority: Priority;
  dueDate?: string;
  completedDate?: string;
  assignees?: string[];
  completionRate?: number;
  decisionsPending?: number;
  decisionsLogged?: number;
  aiRisk?: RiskLevel;
  dependencies?: string[];
  inventoryLink?: {
    items?: string[];
    alerts?: string[];
  };
  currentPhase?: string;
  autoGenerated?: boolean;
  aiAgent?: string;
  awaitingApproval?: boolean;
  outcomes?: string;
};

export type BoardState = Record<ColumnKey, Project[]>;

export type StatDatum = {
  value: number;
  trend?: string;
  alert?: boolean;
  success?: boolean;
};

export type ProjectStats = {
  activeProjects: StatDatum;
  atRisk: StatDatum;
  dueThisWeek: StatDatum;
  aiGenerated: StatDatum;
  decisionsPending: StatDatum;
  completedMtd: StatDatum;
};

export type DecisionAlternative = {
  option: string;
  aiScore: number;
  [key: string]: string | number;
};

export type DecisionNoiseFactor = {
  detected: boolean;
  severity?: "low" | "medium" | "high";
  description?: string;
};

export type Decision = {
  id: string;
  title: string;
  module: string;
  stakes: Priority;
  status: string;
  requester: string;
  created: string;
  deadline: string;
  context: Record<string, string | number>;
  alternatives: DecisionAlternative[];
  criteria: string[];
  noiseFactors: Record<string, DecisionNoiseFactor>;
  aiRecommendation: {
    choice: string;
    confidence: number;
    reasoning: string;
  };
  stakeholders: string[];
};

export type DecisionMetrics = {
  totalDecisions: number;
  pendingDecisions: number;
  avgDecisionTime: string;
  consistencyScore: number;
  noiseReduction: string;
  aiAcceptanceRate: number;
  overdueDecisions: number;
};

export type ExecutionProjectsResponse = {
  board: BoardState;
  stats: ProjectStats;
  updatedAt: string;
};

export type DecisionRegistryResponse = {
  decisions: Decision[];
  metrics: DecisionMetrics;
  updatedAt: string;
};
