import { InventoryPayload } from "./types";

export const inventoryPayloadMock: InventoryPayload = {
  documents: [
    {
      id: "PI-2025-0001",
      number: "PI2025-0001",
      type: "cycle",
      status: "counting",
      plant: "1000",
      storageLocation: "FG01",
      controller: "JSMITH",
      accuracy: 98.6,
      varianceValue: 1125,
      progress: 0.64,
      scheduledDate: "2025-11-18T09:00:00Z",
      bins: [
        {
          id: "bin-01",
          bin: "300-A-01",
          material: "FG-201",
          description: "Cold Brew 12oz",
          batch: "B20251115-01",
          bookQty: 480,
          countQty: 475,
          unit: "EA",
          variance: -5,
          status: "counted",
          countedBy: "JSMITH",
          countedAt: "09:42",
          notes: "Pallet short pick",
        },
        {
          id: "bin-02",
          bin: "300-A-02",
          material: "FG-202",
          description: "Nitro Brew 12oz",
          batch: "B20251115-02",
          bookQty: 360,
          countQty: null,
          unit: "EA",
          variance: null,
          status: "pending",
        },
        {
          id: "bin-03",
          bin: "300-A-03",
          material: "RM-8820",
          description: "Arabica Beans",
          bookQty: 2400,
          countQty: 2550,
          unit: "KG",
          variance: 150,
          status: "recount",
          countedBy: "MJOHNSON",
          countedAt: "09:55",
          requiresRecount: true,
          notes: "Variance > 5%",
        },
      ],
    },
    {
      id: "PI-2025-0002",
      number: "PI2025-0002",
      type: "annual",
      status: "released",
      plant: "2000",
      storageLocation: "RM01",
      controller: "SCHEN",
      accuracy: 0,
      varianceValue: 0,
      progress: 0,
      scheduledDate: "2025-11-20T08:00:00Z",
      bins: [],
    },
  ],
  waveTasks: [
    { id: "wave-01", label: "Wave 431 - Cooler", location: "WH01 / Zone A", bins: 47, owner: "Team Indigo", eta: "Due 12:00", status: "counting" },
    { id: "wave-02", label: "Wave 432 - Ambient", location: "WH02 / Zone C", bins: 63, owner: "Team Gold", eta: "Starts 14:00", status: "precheck" },
    { id: "wave-03", label: "Wave 399 - Returns", location: "WH03 / Dock", bins: 12, owner: "Team Flex", eta: "Recount", status: "recount" },
  ],
  varianceInsights: [
    { reason: "Unrecorded Movements", count: 14, value: 7800, severity: "high" },
    { reason: "Counting Errors", count: 32, value: 2100, severity: "medium" },
    { reason: "Damage/Scrap", count: 6, value: 1200, severity: "low" },
    { reason: "System Posting", count: 3, value: 540, severity: "low" },
  ],
  accuracyTrend: [
    { month: "Jul", value: 95.2 },
    { month: "Aug", value: 95.9 },
    { month: "Sep", value: 96.8 },
    { month: "Oct", value: 97.4 },
    { month: "Nov", value: 98.1 },
  ],
  abcPrograms: [
    { bucket: "A", volume: "$2.8M", frequency: "Every 7 days", coverage: 92 },
    { bucket: "B", volume: "$910K", frequency: "Every 30 days", coverage: 78 },
    { bucket: "C", volume: "$240K", frequency: "Quarterly", coverage: 63 },
  ],
  mobileQueue: [
    { id: "task-1001", bin: "FG-ZN-118", material: "FG-309", priority: "high", instructions: "Scan pallet + capture image" },
    { id: "task-1002", bin: "RM-CH-204", material: "RM-991", priority: "medium", instructions: "Verify batch/serial" },
    { id: "task-1003", bin: "PCK-01-044", material: "PK-110", priority: "low", instructions: "Spot count 5 cartons" },
  ],
};
